M48
; DRILL file {KiCad (6.0.7)} date Wed Aug 10 04:42:45 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-10T04:42:45-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X95.25Y-69.85
X95.25Y-130.81
X151.13Y-69.85
X151.13Y-130.81
T0
M30
